/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSongsRouteImport } from './routes/app/songs'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppArtistsIndexRouteImport } from './routes/app/artists/index'
import { Route as AppAlbumsIndexRouteImport } from './routes/app/albums/index'
import { Route as AppArtistsArtistIdRouteImport } from './routes/app/artists/$artistId'
import { Route as AppAlbumsAlbumIdRouteImport } from './routes/app/albums/$albumId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSongsRoute = AppSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArtistsIndexRoute = AppArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumsIndexRoute = AppAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArtistsArtistIdRoute = AppArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumsAlbumIdRoute = AppAlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/search': typeof AppSearchRoute
  '/app/songs': typeof AppSongsRoute
  '/app/': typeof AppIndexRoute
  '/app/albums/$albumId': typeof AppAlbumsAlbumIdRoute
  '/app/artists/$artistId': typeof AppArtistsArtistIdRoute
  '/app/albums': typeof AppAlbumsIndexRoute
  '/app/artists': typeof AppArtistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/search': typeof AppSearchRoute
  '/app/songs': typeof AppSongsRoute
  '/app': typeof AppIndexRoute
  '/app/albums/$albumId': typeof AppAlbumsAlbumIdRoute
  '/app/artists/$artistId': typeof AppArtistsArtistIdRoute
  '/app/albums': typeof AppAlbumsIndexRoute
  '/app/artists': typeof AppArtistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/search': typeof AppSearchRoute
  '/app/songs': typeof AppSongsRoute
  '/app/': typeof AppIndexRoute
  '/app/albums/$albumId': typeof AppAlbumsAlbumIdRoute
  '/app/artists/$artistId': typeof AppArtistsArtistIdRoute
  '/app/albums/': typeof AppAlbumsIndexRoute
  '/app/artists/': typeof AppArtistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/search'
    | '/app/songs'
    | '/app/'
    | '/app/albums/$albumId'
    | '/app/artists/$artistId'
    | '/app/albums'
    | '/app/artists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/search'
    | '/app/songs'
    | '/app'
    | '/app/albums/$albumId'
    | '/app/artists/$artistId'
    | '/app/albums'
    | '/app/artists'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/search'
    | '/app/songs'
    | '/app/'
    | '/app/albums/$albumId'
    | '/app/artists/$artistId'
    | '/app/albums/'
    | '/app/artists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/songs': {
      id: '/app/songs'
      path: '/songs'
      fullPath: '/app/songs'
      preLoaderRoute: typeof AppSongsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/artists/': {
      id: '/app/artists/'
      path: '/artists'
      fullPath: '/app/artists'
      preLoaderRoute: typeof AppArtistsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/albums/': {
      id: '/app/albums/'
      path: '/albums'
      fullPath: '/app/albums'
      preLoaderRoute: typeof AppAlbumsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/artists/$artistId': {
      id: '/app/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/app/artists/$artistId'
      preLoaderRoute: typeof AppArtistsArtistIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/albums/$albumId': {
      id: '/app/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/app/albums/$albumId'
      preLoaderRoute: typeof AppAlbumsAlbumIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSearchRoute: typeof AppSearchRoute
  AppSongsRoute: typeof AppSongsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumsAlbumIdRoute: typeof AppAlbumsAlbumIdRoute
  AppArtistsArtistIdRoute: typeof AppArtistsArtistIdRoute
  AppAlbumsIndexRoute: typeof AppAlbumsIndexRoute
  AppArtistsIndexRoute: typeof AppArtistsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSearchRoute: AppSearchRoute,
  AppSongsRoute: AppSongsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumsAlbumIdRoute: AppAlbumsAlbumIdRoute,
  AppArtistsArtistIdRoute: AppArtistsArtistIdRoute,
  AppAlbumsIndexRoute: AppAlbumsIndexRoute,
  AppArtistsIndexRoute: AppArtistsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
